apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
      - name: canary-container
        image: canary-app:v1
        ports:
        - containerPort: 3000
