apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app-v2
  template:
    metadata:
      labels:
        app: canary-app-v2
    spec:
      containers:
      - name: canary-container-v2
        image: canary-app:v2
        ports:
        - containerPort: 3000
